name: CI

on:
  push:
  pull_request:

env:
  node_version: '20.x'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
      - run: npm ci --prefer-offline
      - run: npm run lint
